Repository IIIIIFive/Lettudy_Client, pull requests merged in 2024-08, with the labels that each got.

#48 [Api/#43]: 룸 API 연동
  package-lock.json
  package.json
  public/assets/images/empty.png
  src/App.tsx
  src/api/queryClient.ts
  src/api/room.api.ts
  src/components/common/Header.tsx
  src/components/common/NormalButton.tsx
  src/components/homepage/RoomItem.tsx
  src/components/room/Attendance.tsx
  src/components/room/AttendanceCard.tsx
  src/components/room/AttendanceList.tsx
  src/components/room/CalendarModal.tsx
  src/components/room/EmptyAttendance.tsx
  src/components/room/MyAttendance.tsx
  src/components/room/Notice.tsx
  src/components/room/StudyCalendar.tsx
  src/components/room/TopSection.tsx
  src/hooks/useAuth.ts
  src/hooks/useHome.ts
  src/hooks/useRoom.ts
  src/hooks/useSchedule.ts
  src/model/room.model.ts
  src/store/roomStore.ts
  src/utils/format.ts
  src/utils/formatDateTime.ts
Labels: fix, API

#51 [Build/#49] 사용되지 않는 변수 제거 및 오류 수정
  src/components/common/modals/Modals.tsx
  src/components/room/StudyCalendar.tsx
  src/pages/CreateNote.tsx
  src/pages/MyPage.tsx
  src/store/modalStore.ts
Labels: build

#52 [Api/#50]: 자료 모음 API 연동
  package-lock.json
  package.json
  src/App.tsx
  src/api/links.api.ts
  src/api/room.api.ts
  src/components/common/Header.tsx
  src/components/link/LinkInput.tsx
  src/components/link/LinkItem.tsx
  src/components/link/LinkList.tsx
  src/components/room/ButtonList.tsx
  src/hooks/useLinks.ts
  src/model/link.model.ts
  src/pages/LinkManager.tsx
Labels: API

#54 [Fix/#53] 버그 수정 및 에러 메시지 변경
  src/components/room/StudyCalendar.tsx
  src/firebase/requestPermission.ts
  src/hooks/useAuth.ts
  src/hooks/useMyPage.ts
  src/hooks/useUserData.ts
  src/main.tsx
  src/pages/MyPage.tsx
Labels: fix

#57 [Api/#56]: 채팅 API 연동
  package-lock.json
  package.json
  src/App.tsx
  src/api/chat.api.ts
  src/components/chat/ChatContent.tsx
  src/components/chat/ChatItem.tsx
  src/components/chat/ChatRoom.tsx
  src/components/chat/socket.ts
  src/components/room/AttendanceCard.tsx
  src/components/room/ButtonList.tsx
  src/constants/storage.ts
  src/hooks/useAuth.ts
  src/hooks/useChat.ts
  src/model/chat.model.ts
  src/model/user.model.ts
  src/utils/formatChatDate.ts
Labels: API

#59 [Fix/#58]: 팀원 뽑기 데이터 연동 및 오류 수정
  public/assets/images/alarm.png
  src/components/chat/ChatItem.tsx
  src/components/chat/ChatRoom.tsx
  src/components/common/Button.tsx
  src/components/common/modals/Modals.tsx
  src/components/homepage/BottomSection.tsx
  src/components/link/LinkList.tsx
  src/components/note/NoteDetail.tsx
  src/components/note/Pagination.tsx
  src/components/room/Attendance.tsx
  src/components/room/AttendanceInfoModal.tsx
  src/components/room/AttendanceList.tsx
  src/components/room/DrawingModal.tsx
  src/components/room/Notice.tsx
  src/components/room/TopSection.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/pages/NoteView.tsx
  src/store/modalStore.ts
Labels: fix, feat, API

#60 [API/#55] 노트 관련 API 연동 및 개선사항 적용
  package-lock.json
  package.json
  src/App.tsx
  src/api/http.ts
  src/api/note.api.ts
  src/components/common/BackButton.tsx
  src/components/link/LinkInput.tsx
  src/components/mypage/StudyRoomList.tsx
  src/components/note/NoteDetail.tsx
  src/components/note/NoteForm.tsx
  src/components/note/NoteList.tsx
  src/components/note/TagInput.tsx
  src/components/note/TagList.tsx
  src/components/room/ButtonList.tsx
  src/data/noteData.ts
  src/firebase/requestPermission.ts
  src/hooks/useAuth.ts
  src/hooks/useHome.ts
  src/hooks/useMyPage.ts
  src/model/note.model.ts
  src/pages/CreateNote.tsx
  src/pages/EditNote.tsx
  src/pages/Login.tsx
  src/pages/NoteView.tsx
  src/store/noteStore.ts
  src/types/quill-image-resize.d.ts
  tsconfig.json
Labels: fix, feat, API

#64 [Fix/#62] 오류 수정
  src/api/http.ts
  src/components/common/BackButton.tsx
  src/components/mypage/StudyRoomList.tsx
  src/components/note/NoteForm.tsx
  src/hooks/useAuth.ts
  src/hooks/useMyPage.ts
  src/pages/MyPage.tsx
Labels: fix

#66 [Fix/#65] 공지 오류 수정
  src/components/room/TopSection.tsx
Labels: fix

#68 [Fix/#67]: api 호출 관련 오류 수정
  src/components/chat/ChatContent.tsx
  src/components/chat/ChatItem.tsx
  src/components/common/Header.tsx
  src/pages/CreateNote.tsx
  src/pages/EditNote.tsx
Labels: fix

#70 [API/#69]: 이미지 업로드 관련 API 연동
  package-lock.json
  src/api/note.api.ts
  src/components/note/NoteForm.tsx
Labels: API

#74 [Fix/#73]: 멘토링 개선사항 적용
  package-lock.json
  package.json
  src/components/chat/ChatItem.tsx
  src/components/homepage/BottomSection.tsx
  src/components/homepage/HomeModals.tsx
  src/components/homepage/RoomList.tsx
  src/components/mypage/EmptyList.tsx
  src/components/room/CalendarModal.tsx
  src/constants/animals.ts
  src/hooks/useLinks.ts
  src/pages/Join.tsx
Labels: fix

#76 [Fix/#75] 뒤로 가기 버튼 수정
  src/components/common/BackButton.tsx
Labels: fix
